import {
  Bot,
  Building2,
  CalendarDays,
  ClipboardList,
  Globe,
  GraduationCap,
  Handshake,
  LayoutDashboard,
  Medal,
  MessageSquare,
  Package,
  Settings,
  Shield,
  Link2,
  ListOrdered,
  Newspaper,
  Trophy,
  User,
  UserRound,
  Users,
  Video,
  Wallet,
  UserCheck,
  Contact,
} from "lucide-react";

export const dashboardNav = [
  {
    title: "Dashboard",
    href: "/dashboard",
    icon: LayoutDashboard,
  },
  {
    title: "Profil użytkownika",
    href: "/profile",
    icon: User,
  },
  {
    title: "Ustawienia aplikacji",
    href: "/settings",
    icon: Settings,
  },
  {
    title: "Profil klubu",
    href: "/club",
    icon: Building2,
  },
  {
    title: "Drużyny",
    href: "/teams",
    icon: Users,
  },
  {
    title: "Zawodnicy",
    href: "/players",
    icon: UserRound,
  },
  {
    title: "Treningi",
    href: "/training",
    icon: CalendarDays,
  },
  {
    title: "Frekwencja",
    href: "/attendance",
    icon: UserCheck,
    audience: "attendance_staff" as const,
  },
  {
    title: "Club CRM",
    href: "/crm",
    icon: Contact,
    audience: "crm_staff" as const,
  },
  {
    title: "Relacje klubu",
    href: "/crm/parents",
    icon: Contact,
    audience: "crm_parent" as const,
  },
  {
    title: "Mecze",
    href: "/matches",
    icon: Trophy,
  },
  {
    title: "Video Center",
    href: "/video",
    icon: Video,
    audience: "video_staff" as const,
  },
  {
    title: "Content Hub",
    href: "/content",
    icon: Newspaper,
    audience: "content_staff" as const,
  },
  {
    title: "Tabela ligowa",
    href: "/matches/league-table",
    icon: ListOrdered,
  },
  {
    title: "Integracje",
    href: "/integrations",
    icon: Link2,
    audience: "integration_staff" as const,
  },
  {
    title: "League Hub",
    href: "/league",
    icon: Medal,
    audience: "league_staff" as const,
  },
  {
    title: "Communication Hub",
    href: "/communication",
    icon: MessageSquare,
    audience: "communication_staff" as const,
  },
  {
    title: "Akademia",
    href: "/academy",
    icon: GraduationCap,
    audience: "academy_staff" as const,
  },
  {
    title: "Panel trenera",
    href: "/training/coach",
    icon: ClipboardList,
  },
  {
    title: "AI Club Manager",
    href: "/ai/manager",
    icon: Bot,
  },
  {
    title: "Zadania AI",
    href: "/ai/tasks",
    icon: Bot,
  },
  {
    title: "Club AI Assistant",
    href: "/ai",
    icon: Bot,
  },
  {
    title: "Sponsorzy",
    href: "/sponsors",
    icon: Handshake,
    audience: "staff" as const,
  },
  {
    title: "Panel sponsora",
    href: "/sponsors/portal",
    icon: Handshake,
    audience: "sponsor" as const,
  },
  {
    title: "Finanse",
    href: "/finance",
    icon: Wallet,
    audience: "finance_staff" as const,
  },
  {
    title: "Moje składki",
    href: "/finance/portal",
    icon: Wallet,
    audience: "parent" as const,
  },
  {
    title: "Magazyn",
    href: "/inventory",
    icon: Package,
    audience: "inventory_staff" as const,
  },
  {
    title: "Mój sprzęt",
    href: "/inventory/portal",
    icon: Package,
    audience: "player" as const,
  },
  {
    title: "Strona klubu",
    href: "/website",
    icon: Globe,
    audience: "website_staff" as const,
  },
  {
    title: "Role i uprawnienia",
    href: "/members",
    icon: Shield,
  },
] as const;
